FROM node:10.16-alpine as builder
WORKDIR '/app'
COPY package.json .
RUN yarn install
COPY . .
RUN yarn build

FROM nginx:1.17-alpine
COPY --from=builder /app/build/ /srv/chris.topher.la/frontend/build