# Development docker-compose file
version: '3.7'
services:
  react-app:
    environment:
      - REACT_APP_API_URL=http://portfolio.dev.topher.la:8080
      - REACT_APP_GOOGLE_ANALYTICS=${REACT_APP_GOOGLE_ANALYTICS}
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"