# Development docker-compose file
version: '3'
services:
  # Database
  database:
    build:
      context: ./server
      dockerfile: Dockerfile_mongodb
    restart: always
    volumes:
      - ./server/data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
    ports:
      - "27017:27017"

  # Server
  node-app:
    restart: on-failure
    build:
      context: ./server
      dockerfile: Dockerfile_node
    depends_on:
      - database
    volumes:
      - ./server:/app
      - /app/node_modules
    links:
      - database
    environment:
      WAIT_HOSTS: database:27017
    ports:
      - "5000:5000"

  # Frontend
  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    depends_on:
      - database
      - node-app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"