FROM node:10.16-alpine
WORKDIR /srv/server
COPY ./package.json ./
RUN yarn install
COPY . .

## Add the wait script to the image
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.5.1/wait /wait
RUN chmod +x /wait

## Launch the wait tool and then your application
CMD /wait && yarn run ${NODE_ENV}