import { ISkill } from "./types";

const skillToImage: ISkill = {
  apiGateway: "aws_api_gateway.png",
  dynamodb: "aws_dynamodb.png",
  lambda: "aws_lambda.png",
  s3: "aws_s3.png",
  sqs: "aws_sqs.png",
  apigee: "apigee.svg",
  bash: "bash.png",
  cypress: "cypress.png",
  docker: "docker.png",
  drupal: "drupal.png",
  elasticsearch: "elasticsearch.png",
  email: "email.png",
  expressJs: "express_js.png",
  fastapi: "fastapi.svg",
  github: "github.png",
  graphql: "graphql.png",
  javascript: "javascript.png",
  jenkins: "jenkins.png",
  jest: "jest.png",
  linkedin: "linkedin.png",
  marker: "marker.png",
  mongodb: "mongodb.png",
  mysql: "mysql.png",
  nextjs: "nextjs.png",
  nodejs: "nodejs.svg",
  nuxt: "nuxt.png",
  php: "php.png",
  postgresql: "postgresql.png",
  python: "python.png",
  rails: "rails.png",
  react: "react.png",
  redis: "redis.png",
  ruby: "ruby.png",
  terraform: "terraform.png",
  typescript: "typescript.png",
  vercel: "vercel.svg",
  vue: "vue.png",
};

export const Skill = {
  skillToImage,
};
