name: Stage Deployment

on:
  pull_request:
    branches: [stage]
    types: [closed]

jobs:
  stage-deployment:
    name: Stage Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Stage To Vercel
        run: curl -s -X POST ${{ secrets.VERCEL_DEPLOY_STAGE_HOOK_URL }}
